/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "autopilot.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GPSBuf, GPSBuf, AUTO)


PB_BIND(IMUBuf, IMUBuf, AUTO)


PB_BIND(BarometerBuf, BarometerBuf, AUTO)


PB_BIND(SensorBuf, SensorBuf, AUTO)


PB_BIND(StateEstimatorBuf, StateEstimatorBuf, AUTO)


PB_BIND(StatusBuf, StatusBuf, AUTO)


PB_BIND(ModeBuf, ModeBuf, AUTO)


PB_BIND(PlaneBuf, PlaneBuf, 2)



