/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "autopilot.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SensorStruct, SensorStruct, AUTO)


PB_BIND(PlaneBuf, PlaneBuf, AUTO)



