function f_cntrl = f_cntrl_Fcn(t,in2)
%f_cntrl_Fcn
%    F_CNTRL = f_cntrl_Fcn(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    21-Oct-2021 11:00:16

p = in2(5,:);
q = in2(6,:);
q1 = in2(1,:);
q2 = in2(2,:);
q3 = in2(3,:);
q4 = in2(4,:);
r = in2(7,:);
f_cntrl = [(p.*q4)./2.0-(q.*q3)./2.0+(q2.*r)./2.0;(p.*q3)./2.0+(q.*q4)./2.0-(q1.*r)./2.0;p.*q2.*(-1.0./2.0)+(q.*q1)./2.0+(q4.*r)./2.0;p.*q1.*(-1.0./2.0)-(q.*q2)./2.0-(q3.*r)./2.0;0.0;0.0;0.0];
