function f = f_Fcn(in1)
%f_Fcn
%    F = f_Fcn(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    25-Oct-2021 23:05:15

p = in1(5,:);
q = in1(6,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
r = in1(7,:);
f = [(p.*q4)./2.0-(q.*q3)./2.0+(q2.*r)./2.0;(p.*q3)./2.0+(q.*q4)./2.0-(q1.*r)./2.0;p.*q2.*(-1.0./2.0)+(q.*q1)./2.0+(q4.*r)./2.0;p.*q1.*(-1.0./2.0)-(q.*q2)./2.0-(q3.*r)./2.0];
