function f = f_Fcn(t,in2)
%F_FCN
%    F = F_FCN(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-May-2021 22:16:12

X = in2(10,:);
Y = in2(11,:);
Z = in2(12,:);
p = in2(13,:);
phi = in2(7,:);
psi = in2(9,:);
q = in2(14,:);
r = in2(15,:);
theta = in2(8,:);
u = in2(4,:);
v = in2(5,:);
w = in2(6,:);
t2 = cos(phi);
t3 = cos(psi);
t4 = cos(theta);
t5 = sin(phi);
t6 = sin(psi);
t7 = sin(theta);
t8 = tan(theta);
t9 = u+1.5e+1;
t10 = 1.0./t4;
f = [-v.*(t2.*t6-t3.*t5.*t7)+w.*(t5.*t6+t2.*t3.*t7)+t3.*t4.*t9;v.*(t2.*t3+t5.*t6.*t7)-w.*(t3.*t5-t2.*t6.*t7)+t4.*t6.*t9;-t7.*t9+t4.*t5.*v+t2.*t4.*w;X-t7.*(4.9e+1./5.0);Y+t4.*t5.*(4.9e+1./5.0);Z+t2.*t4.*(4.9e+1./5.0);p+q.*t5.*t8+r.*t2.*t8;q.*t2-r.*t5;q.*t5.*t10+r.*t2.*t10];
