function f = f_Fcn(in1,in2,in3)
%f_Fcn
%    F = f_Fcn(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    16-Nov-2021 11:04:06

fx = in2(4,:);
fy = in2(5,:);
fz = in2(6,:);
gravVec0Sym1 = in3(1,:);
gravVec0Sym2 = in3(2,:);
gravVec0Sym3 = in3(3,:);
p = in2(1,:);
q = in2(2,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
r = in2(3,:);
vD = in1(10,:);
vE = in1(9,:);
vN = in1(8,:);
t2 = q1.^2;
t3 = q2.^2;
t4 = q3.^2;
t5 = q4.^2;
t6 = q1.*q2.*2.0;
t7 = q1.*q3.*2.0;
t8 = q1.*q4.*2.0;
t9 = q2.*q3.*2.0;
t10 = q2.*q4.*2.0;
t11 = q3.*q4.*2.0;
t12 = -t3;
t13 = -t4;
t14 = -t5;
f = [(p.*q4)./2.0-(q.*q3)./2.0+(q2.*r)./2.0;(p.*q3)./2.0+(q.*q4)./2.0-(q1.*r)./2.0;p.*q2.*(-1.0./2.0)+(q.*q1)./2.0+(q4.*r)./2.0;p.*q1.*(-1.0./2.0)-(q.*q2)./2.0-(q3.*r)./2.0;vN;vE;vD;-gravVec0Sym1+fz.*(t7+t10)+fy.*(t6-t11)+fx.*(t2+t5+t12+t13);-gravVec0Sym2+fx.*(t6+t11)-fz.*(t8-t9)-fy.*(t2+t4+t12+t14);-gravVec0Sym3+fy.*(t8+t9)+fx.*(t7-t10)-fz.*(t2+t3+t13+t14);0.0;0.0;0.0];
