function G = G_jac_Fcn(in1,in2)
%G_jac_Fcn
%    G = G_jac_Fcn(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    21-Oct-2021 11:00:17

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = q1./2.0;
t3 = q2./2.0;
t4 = q3./2.0;
t5 = q4./2.0;
t6 = -t2;
t7 = -t3;
t8 = -t4;
G = reshape([t5,t4,t7,t6,t8,t5,t2,t7,t3,t6,t5,t8],[4,3]);
