function h = h_Fcn(in1,in2,in3)
%h_Fcn
%    H = h_Fcn(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    24-Sep-2021 14:29:11

D = in1(3,:);
E = in1(2,:);
N = in1(1,:);
magVec01 = in3(1,:);
magVec02 = in3(2,:);
magVec03 = in3(3,:);
q1 = in1(7,:);
q2 = in1(8,:);
q3 = in1(9,:);
q4 = in1(10,:);
u = in1(4,:);
v = in1(5,:);
w = in1(6,:);
t2 = q1.^2;
t3 = q2.^2;
t4 = q3.^2;
t5 = q4.^2;
t6 = q1.*q2.*2.0;
t7 = q1.*q3.*2.0;
t8 = q1.*q4.*2.0;
t9 = q2.*q3.*2.0;
t10 = q2.*q4.*2.0;
t11 = q3.*q4.*2.0;
t12 = -t9;
t13 = -t11;
t14 = -t3;
t15 = -t4;
t16 = -t5;
t17 = t6+t11;
t18 = t7+t10;
t19 = t6+t13;
t20 = t8+t12;
t21 = t2+t5+t14+t15;
t22 = t2+t4+t14+t16;
h = [N;E;D;sqrt(abs(u).^2+abs(v).^2+abs(w).^2);magVec02.*t17+magVec01.*t21+magVec03.*(t7-t10);magVec03.*(t8+t9)+magVec01.*t19-magVec02.*t22;magVec01.*t18-magVec02.*t20-magVec03.*(t2+t3+t15+t16);atan2(t17.*u-t22.*v-t20.*w,t21.*u+t19.*v+t18.*w);D];
