function h = h_Fcn(in1,in2,in3)
%h_Fcn
%    H = h_Fcn(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    21-Oct-2021 11:00:17

magVec01 = in3(1,:);
magVec02 = in3(2,:);
magVec03 = in3(3,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = q1.^2;
t3 = q2.^2;
t4 = q3.^2;
t5 = q4.^2;
t6 = q1.*q2.*2.0;
t7 = q1.*q3.*2.0;
t8 = q1.*q4.*2.0;
t9 = q2.*q3.*2.0;
t10 = q2.*q4.*2.0;
t11 = q3.*q4.*2.0;
t12 = -t3;
t13 = -t4;
t14 = -t5;
h = [magVec02.*(t6+t11)+magVec03.*(t7-t10)+magVec01.*(t2+t5+t12+t13);magVec03.*(t8+t9)+magVec01.*(t6-t11)-magVec02.*(t2+t4+t12+t14);magVec01.*(t7+t10)-magVec02.*(t8-t9)-magVec03.*(t2+t3+t13+t14)];
