function H = H_jac_Fcn(in1,in2)
%H_jac_Fcn
%    H = H_jac_Fcn(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    03-Nov-2021 21:20:11

magVec0Sym1 = in2(1,:);
magVec0Sym2 = in2(2,:);
magVec0Sym3 = in2(3,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = magVec0Sym1.*q1.*2.0;
t3 = magVec0Sym1.*q2.*2.0;
t4 = magVec0Sym2.*q1.*2.0;
t5 = magVec0Sym1.*q3.*2.0;
t6 = magVec0Sym2.*q2.*2.0;
t7 = magVec0Sym3.*q1.*2.0;
t8 = magVec0Sym1.*q4.*2.0;
t9 = magVec0Sym2.*q3.*2.0;
t10 = magVec0Sym3.*q2.*2.0;
t11 = magVec0Sym2.*q4.*2.0;
t12 = magVec0Sym3.*q3.*2.0;
t13 = magVec0Sym3.*q4.*2.0;
t14 = -t4;
t15 = -t5;
t16 = -t10;
t17 = t2+t6+t12;
t18 = t3+t13+t14;
t19 = t7+t11+t15;
t20 = t8+t9+t16;
H = reshape([t17,t18,t5-t7-t11,0.0,0.0,0.0,-t3+t4-t13,t17,t20,0.0,0.0,0.0,t19,-t8-t9+t10,t17,0.0,0.0,0.0,t20,t19,t18,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,10]);
