function H = H_jac_Fcn(in1,in2,in3)
%H_jac_Fcn
%    H = H_jac_Fcn(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    21-Oct-2021 11:00:17

magVec01 = in3(1,:);
magVec02 = in3(2,:);
magVec03 = in3(3,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = magVec01.*q1.*2.0;
t3 = magVec01.*q2.*2.0;
t4 = magVec02.*q1.*2.0;
t5 = magVec01.*q3.*2.0;
t6 = magVec02.*q2.*2.0;
t7 = magVec03.*q1.*2.0;
t8 = magVec01.*q4.*2.0;
t9 = magVec02.*q3.*2.0;
t10 = magVec03.*q2.*2.0;
t11 = magVec02.*q4.*2.0;
t12 = magVec03.*q3.*2.0;
t13 = magVec03.*q4.*2.0;
t14 = -t4;
t15 = -t5;
t16 = -t10;
t17 = t2+t6+t12;
t18 = t3+t13+t14;
t19 = t7+t11+t15;
t20 = t8+t9+t16;
H = reshape([t17,t18,t5-t7-t11,-t3+t4-t13,t17,t20,t19,-t8-t9+t10,t17,t20,t19,t18],[3,4]);
