function I_C_B = I_C_B_Fcn(phi,theta,psi)
%I_C_B_FCN
%    I_C_B = I_C_B_FCN(PHI,THETA,PSI)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-May-2021 22:16:12

t2 = cos(phi);
t3 = cos(psi);
t4 = cos(theta);
t5 = sin(phi);
t6 = sin(psi);
t7 = sin(theta);
I_C_B = reshape([t3.*t4,t4.*t6,-t7,-t2.*t6+t3.*t5.*t7,t2.*t3+t5.*t6.*t7,t4.*t5,t5.*t6+t2.*t3.*t7,-t3.*t5+t2.*t6.*t7,t2.*t4],[3,3]);
