function r0_ECEF = LatLonAlt2ECEF_Fcn(Lat,Lon,Alt)
%LATLONALT2ECEF_FCN
%    R0_ECEF = LATLONALT2ECEF_FCN(LAT,LON,ALT)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-Jun-2021 23:09:53

t2 = (Lat.*pi)./1.8e+2;
t3 = (Lon.*pi)./1.8e+2;
t4 = cos(t2);
t5 = sin(t2);
t6 = t4.^2;
t7 = t5.^2;
t8 = t6.*4.0680631590769e+13;
t9 = t7.*4.040829998465916e+13;
t10 = t8+t9;
t11 = 1.0./sqrt(t10);
t12 = t11.*4.0680631590769e+13;
t13 = Alt+t12;
r0_ECEF = [t4.*t13.*cos(t3);t4.*t13.*sin(t3);t5.*(Alt+t11.*4.040829998465915e+13)];
