function Q = Q_Fcn(dT)
%Q_Fcn
%    Q = Q_Fcn(dT)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    25-Oct-2021 23:05:16

Q = reshape([3.604127151283208e-4,0.0,0.0,0.0,4.268449580753373e-4,0.0,0.0,0.0,7.669213132220835e-4],[3,3]);
