function NED_C_ECEF = TECEF2NED_Fcn(in1)
%TECEF2NED_FCN
%    NED_C_ECEF = TECEF2NED_FCN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-Jun-2021 19:40:44

r0_ECEF1 = in1(1,:);
r0_ECEF2 = in1(2,:);
r0_ECEF3 = in1(3,:);
t2 = abs(r0_ECEF1);
t3 = abs(r0_ECEF2);
t4 = abs(r0_ECEF3);
t5 = r0_ECEF1.^2;
t6 = r0_ECEF2.^2;
t7 = r0_ECEF3.^2;
t8 = t2.^2;
t9 = t3.^2;
t10 = t4.^2;
t11 = t5+t6;
t12 = 1.0./sqrt(t11);
t13 = t8+t9+t10;
t14 = 1.0./t13;
t15 = 1.0./sqrt(t13);
t16 = t7.*t14;
t17 = -t16;
t18 = t17+1.0;
t19 = sqrt(t18);
NED_C_ECEF = reshape([-r0_ECEF1.*r0_ECEF3.*t12.*t15,-r0_ECEF2.*t12,-r0_ECEF1.*t12.*t19,-r0_ECEF2.*r0_ECEF3.*t12.*t15,r0_ECEF1.*t12,-r0_ECEF2.*t12.*t19,t19,0.0,-r0_ECEF3.*t15],[3,3]);
