//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
// File: f_Fcn.cpp
//
// MATLAB Coder version            : 5.0
// C/C++ source code generated on  : 02-Jun-2021 15:49:07
//

// Include Files
#include "f_Fcn.h"

// Function Definitions

//
// F_FCN
//     F = F_FCN(T,IN2)
// Arguments    : double t
//                const double in2[16]
//                double f[10]
// Return Type  : void
//
void f_Fcn(double, const double in2[16], double f[10])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7_tmp;
  double t7;
  double t8_tmp;
  double t8;
  double t9_tmp;
  double t9;
  double t10_tmp;
  double t10;
  double t11;

  //     This function was generated by the Symbolic Math Toolbox version 8.5.
  //     02-Jun-2021 15:48:49
  t2 = in2[6] * in2[6];
  t3 = in2[7] * in2[7];
  t4 = in2[8] * in2[8];
  t5 = in2[9] * in2[9];
  t6 = in2[6] * in2[7] * 2.0;
  t7_tmp = in2[6] * in2[8];
  t7 = t7_tmp * 2.0;
  t8_tmp = in2[6] * in2[9];
  t8 = t8_tmp * 2.0;
  t9_tmp = in2[7] * in2[8];
  t9 = t9_tmp * 2.0;
  t10_tmp = in2[7] * in2[9];
  t10 = t10_tmp * 2.0;
  t11 = in2[8] * in2[9] * 2.0;
  f[0] = (in2[3] * (((t2 + t5) + -t3) + -t4) + in2[5] * (t7 + t10)) + in2[4] *
    (t6 - t11);
  f[1] = (-in2[4] * (((t2 + t4) + -t3) + -t5) + in2[3] * (t6 + t11)) - in2[5] *
    (t8 - t9);
  f[2] = (-in2[5] * (((t2 + t3) + -t4) + -t5) + in2[4] * (t8 + t9)) + in2[3] *
    (t7 - t10);
  f[3] = (in2[10] + t7_tmp * 19.6) - t10_tmp * 19.6;
  f[4] = (in2[11] + t8_tmp * 19.6) + t9_tmp * 19.6;
  f[5] = (((in2[12] - t2 * 9.8) - t3 * 9.8) + t4 * 9.8) + t5 * 9.8;
  f[6] = (in2[13] * in2[9] / 2.0 - in2[14] * in2[8] / 2.0) + in2[7] * in2[15] /
    2.0;
  f[7] = (in2[13] * in2[8] / 2.0 + in2[14] * in2[9] / 2.0) - in2[6] * in2[15] /
    2.0;
  f[8] = (in2[13] * in2[7] * -0.5 + in2[14] * in2[6] / 2.0) + in2[9] * in2[15] /
    2.0;
  f[9] = (in2[13] * in2[6] * -0.5 - in2[14] * in2[7] / 2.0) - in2[8] * in2[15] /
    2.0;
}

//
// File trailer for f_Fcn.cpp
//
// [EOF]
//
