/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_AUTOPILOT_PB_H_INCLUDED
#define PB_AUTOPILOT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Combine Sensors */
typedef struct _SensorStruct { 
    /* GPSStruct GPS = 1;
 IMUStruct IMU = 2;
 BarometerStruct baro = 3; */
    int32_t test; 
} SensorStruct;

/* Plane Object is highest */
typedef struct _PlaneBuf { 
    float delt; 
    bool has_sensors;
    SensorStruct sensors; /* StateEstimatorStruct stateEstimator = 3;
 StatusStruct status = 4;
 ModeStruct mode = 5; */
} PlaneBuf;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SensorStruct_init_default                {0}
#define PlaneBuf_init_default                    {0, false, SensorStruct_init_default}
#define SensorStruct_init_zero                   {0}
#define PlaneBuf_init_zero                       {0, false, SensorStruct_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define SensorStruct_test_tag                    1
#define PlaneBuf_delt_tag                        1
#define PlaneBuf_sensors_tag                     2

/* Struct field encoding specification for nanopb */
#define SensorStruct_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    test,              1)
#define SensorStruct_CALLBACK NULL
#define SensorStruct_DEFAULT NULL

#define PlaneBuf_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    delt,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sensors,           2)
#define PlaneBuf_CALLBACK NULL
#define PlaneBuf_DEFAULT NULL
#define PlaneBuf_sensors_MSGTYPE SensorStruct

extern const pb_msgdesc_t SensorStruct_msg;
extern const pb_msgdesc_t PlaneBuf_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SensorStruct_fields &SensorStruct_msg
#define PlaneBuf_fields &PlaneBuf_msg

/* Maximum encoded size of messages (where known) */
#define PlaneBuf_size                            18
#define SensorStruct_size                        11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
